package com.vitalvetcris.app;
import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.os.*; import android.webkit.*; import android.widget.Toast; import java.text.SimpleDateFormat; import java.util.*;
public class MainActivity extends Activity {
 public static final String CHANNEL_ID="vital_vet_citas"; private WebView web;
 @Override public void onCreate(Bundle state){super.onCreate(state);createChannel();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);web.setWebViewClient(new WebViewClient());web.addJavascriptInterface(new AndroidBridge(),"Android");web.loadUrl("file:///android_asset/index.html");setContentView(web);}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"Recordatorios de citas",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Avisos diez minutos antes de las citas veterinarias");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 public class AndroidBridge {@JavascriptInterface public void scheduleNotification(String isoDate,String title,String body,String appointmentId){try{Date date=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm",Locale.US).parse(isoDate);long at=date.getTime()-10*60*1000L;if(at<=System.currentTimeMillis())return;Intent i=new Intent(MainActivity.this,ReminderReceiver.class);i.putExtra("title",title);i.putExtra("body",body);PendingIntent pi=PendingIntent.getBroadcast(MainActivity.this,appointmentId.hashCode(),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);if(Build.VERSION.SDK_INT>=31&&!am.canScheduleExactAlarms())am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);else am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,at,pi);runOnUiThread(()->Toast.makeText(MainActivity.this,"Aviso programado 10 minutos antes",Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,"No se pudo programar el aviso",Toast.LENGTH_SHORT).show());}}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
